//Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNTcxMTk1LCJleHAiOjE2NjE1NzE3OTV9.KKmy_RlSrSIe6RQJQT0TkvlPbVEoHec3YIltWvvYPN4

###
POST http://localhost:8080/join
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234"
}

###
PUT http://localhost:8080/api/post/38
Content-Type: application/json

###

POST http://localhost:8080/api/auth/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODIwNTUyLCJleHAiOjE2NjE4MjExNTJ9.iRyOo_jWBQbWvoNrN-_Nf1p-nfnTgeltVlPkRMayrZw

{
  "title": "글 제목입니다 2222",
  "content": "글 내용입니다 2222",
  "imgUrl": "aaa"
}

###
POST http://localhost:8080/api/auth/post/42/comment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzY0MzQ0LCJleHAiOjE2NjE3NjQ5NDR9.uUc9ffolPTGnBOr3AvtRvLYpxyWO4Ap-a4VeAxGD3sU

{
  "comment": "댓글 내용입니다 111"
}

###
PUT http://localhost:8080/api/auth/post/42/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzY0MzQ0LCJleHAiOjE2NjE3NjQ5NDR9.uUc9ffolPTGnBOr3AvtRvLYpxyWO4Ap-a4VeAxGD3sU


###
POST http://localhost:8080/api/auth/comment/43/recomment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzUxMzc0LCJleHAiOjE2NjE3NTE5NzR9.F7SKDccTgUi9hDkUrEMKhHdYWpblxRvJWzlXhxj9RPA

{
  "comment": "대댓글 내용입니다 111"
}

###
GET http://localhost:8080/api/comment/42
Content-Type: application/json


###
GET http://localhost:8080/api/comment/43/recomment
Content-Type: application/json

###
GET http://localhost:8080/api/post/42
Content-Type: application/json


###
PUT http://localhost:8080/api/auth/recomment/46/like/false
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzc2MzE4LCJleHAiOjE2NjE3NzY5MTh9.gxKS9rFAc4rkBqIAkaTtwgku3ZjxHV8W1uQwroYTEqU

###
PUT http://localhost:8080/api/auth/comment/43/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzc2MzE4LCJleHAiOjE2NjE3NzY5MTh9.gxKS9rFAc4rkBqIAkaTtwgku3ZjxHV8W1uQwroYTEqU


###
GET http://localhost:8080/api/auth/mypage
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODM1NTI0LCJleHAiOjE2NjE4MzYxMjR9.frZqqGCBqeFXDMmXDA2Om0IJnGqgghI8q2YiJ4zVHQY
