//Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNTcxMTk1LCJleHAiOjE2NjE1NzE3OTV9.KKmy_RlSrSIe6RQJQT0TkvlPbVEoHec3YIltWvvYPN4

###
POST http://localhost:8080/join
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234"
}

###
PUT http://localhost:8080/api/post/38
Content-Type: application/json

###

POST http://localhost:8080/api/auth/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzUxMzc0LCJleHAiOjE2NjE3NTE5NzR9.F7SKDccTgUi9hDkUrEMKhHdYWpblxRvJWzlXhxj9RPA

{
  "title": "글 제목입니다 2222",
  "content": "글 내용입니다 2222",
  "imgUrl": "aaa"
}

###
POST http://localhost:8080/api/auth/post/42/comment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzUxMzc0LCJleHAiOjE2NjE3NTE5NzR9.F7SKDccTgUi9hDkUrEMKhHdYWpblxRvJWzlXhxj9RPA

{
  "comment": "댓글 내용입니다 111"
}

###
PUT http://localhost:8080/api/auth/post/38/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzQ2OTQ3LCJleHAiOjE2NjE3NDc1NDd9.Q8Cm4uyROid5QzMbwTLwqs_vg_SOsNMijuG_CI_k1oY


###
POST http://localhost:8080/api/auth/comment/43/recomment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzUxMzc0LCJleHAiOjE2NjE3NTE5NzR9.F7SKDccTgUi9hDkUrEMKhHdYWpblxRvJWzlXhxj9RPA

{
  "comment": "대댓글 내용입니다 111"
}

###
GET http://localhost:8080/api/comment/43/recomment
Content-Type: application/json