//Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNTcxMTk1LCJleHAiOjE2NjE1NzE3OTV9.KKmy_RlSrSIe6RQJQT0TkvlPbVEoHec3YIltWvvYPN4

###
POST http://localhost:8080/join
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username":"jeeyeon",
  "password":"1234"
}

###
PUT http://localhost:8080/api/post/38
Content-Type: application/json

###

POST http://localhost:8080/api/auth/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ0MDMyLCJleHAiOjE2NjE4NDQ2MzJ9.rcIwKrxk6hpabnX1IHhuX29Hsyc0GQb7AkBe0qol09c

{
  "title": "글 제목입니다 2222",
  "content": "글 내용입니다 2222",
  "imgUrl": "aaa"
}

###
POST http://localhost:8080/api/auth/post/57/comment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ0OTQzLCJleHAiOjE2NjE4NDU1NDN9.Pkj28aRMyxopz8nEUZZUsdxxXEbODhWBxJPCgz1gEac

{
  "comment": "댓글 내용입니다 111"
}

###
PUT http://localhost:8080/api/auth/post/42/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxNzY0MzQ0LCJleHAiOjE2NjE3NjQ5NDR9.uUc9ffolPTGnBOr3AvtRvLYpxyWO4Ap-a4VeAxGD3sU


###
POST http://localhost:8080/api/auth/comment/58/recomment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ0OTQzLCJleHAiOjE2NjE4NDU1NDN9.Pkj28aRMyxopz8nEUZZUsdxxXEbODhWBxJPCgz1gEac

{
  "comment": "대댓글 내용입니다 111"
}

###
GET http://localhost:8080/api/comment/57
Content-Type: application/json


###
GET http://localhost:8080/api/comment/58/recomment
Content-Type: application/json

###
GET http://localhost:8080/api/post/57
Content-Type: application/json


###
PUT http://localhost:8080/api/auth/recomment/61/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ0ODY2LCJleHAiOjE2NjE4NDU0NjZ9.lmjgdlsu9qz6qBQH0838a47y1gJ-4Sb7V83Q1Jv_twM

###
PUT http://localhost:8080/api/auth/comment/58/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ1NjgwLCJleHAiOjE2NjE4NDYyODB9.YCl3utiUEhHmDkyhHkj0ZoVDxi5em5tdjNhmrX_tw88

###

PUT http://localhost:8080/api/auth/post/57/like/true
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODQ2NTkxLCJleHAiOjE2NjE4NDcxOTF9.x4t4CZsQAfmKGS_gmvTRAYd_zL3AwcW8mtqDsOKCK5A


###
GET http://localhost:8080/api/auth/mypage
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWV5ZW9uIiwiaWF0IjoxNjYxODM1NTI0LCJleHAiOjE2NjE4MzYxMjR9.frZqqGCBqeFXDMmXDA2Om0IJnGqgghI8q2YiJ4zVHQY
